---

# Credentials for CVP and EOS Switches
ansible_user: admin
ansible_password: admin
ansible_network_os: arista.eos.eos
# Configure privilege escalation
ansible_become: true
ansible_become_method: enable
# HTTPAPI configuration
ansible_connection: httpapi
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)
avd_data_validation_mode: error

# Local Users
local_users:
  - name: admin
    privilege: 15
    role: network-admin
    sha512_password: "$6$a1IgOsrvBrJEOz1S$Z3/AwDi0B.8cAAJAGZWYgXsqxn/qdJm0T075VAvysuU0w62lFgjvw3KfFLdz0hhokIKqydnfAgADnzUFU/OfP."


# AAA
aaa_authorization:
  exec:
    default: local

# OOB Management network default gateway.
mgmt_gateway: 172.31.0.1
mgmt_interface: Management1
mgmt_interface_vrf: MGMT

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp:
  servers:
    - name: time.google.com
      # iburst: true
      # local_interface: Management0
      vrf: MGMT

# Domain/DNS
dns_domain: atd.lab
ip_name_servers:
  - ip_address: 8.8.8.8
    vrf: MGMT

# TerminAttr
daemon_terminattr:
  # Address of the gRPC server on CloudVision
  # TCP 9910 is used on on-prem
  # TCP 443 is used on CV as a Service
  cvaddrs: # For single cluster
    - apiserver.cv-staging.corp.arista.io:443
  # Authentication scheme used to connect to CloudVision
  cvauth:
    method: token-secure
    token_file: "/tmp/cv-onboarding-token"
  # Exclude paths from Sysdb on the ingest side
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  # Exclude paths from the shared memory table
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  disable_aaa: true
  cvvrf: MGMT

# daemon TerminAttr
#    exec /usr/bin/TerminAttr -cvaddr=apiserver.cv-staging.corp.arista.io:443 -cvcompression=gzip -taillogs -cvauth=token-secure,/tmp/cv-onboarding-token -cvvrf=MGMT -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent --disableaaa
#    no shutdown
# !

# Point to Point Links MTU Override for Lab
p2p_uplinks_mtu: 1500

# # CVP node variables
# cv_collection: v3
# execute_tasks: true
