---
fabric_name: DC_FABRIC

# Spine Switches
spine:
  defaults:
    platform: cEOS
    bgp_as: 65000
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    loopback_ipv4_pool: 1.1.1.0/24
    loopback_ipv4_offset: 98
  node_groups:
    - group: SPINES
      nodes:
        - name: SPINE1
          id: 1
          mgmt_ip: 172.31.0.22/23
        - name: SPINE2
          id: 2
          mgmt_ip: 172.31.0.23/23

# Leaf Switches
l3leaf:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 1.1.1.0/24
    vtep_loopback_ipv4_pool: 2.2.2.0/24
    mlag_peer_ipv4_pool: 10.1.253.0/24
    mlag_peer_l3_ipv4_pool: 10.1.254.0/24
    uplink_ipv4_pool: 10.0.0.0/24
    virtual_router_mac_address: aa:aa:bb:bb:cc:cc
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    uplink_switches: [ SPINE1, SPINE2 ]
    uplink_interfaces: [ Ethernet1, Ethernet2 ]
    mlag_interfaces: [ Ethernet3, Ethernet4 ]
    structured_config:
      vxlan_interface:
        vxlan1:
          eos_cli: |
            icmp helper
            icmp helper vrf Red
  node_groups:
    - group: POD1
      bgp_as: 65001
      filter:
        tags: [ "Web" ]
      nodes:
        - name: LEAF1
          id: 1
          mgmt_ip: 172.31.0.27/23
          uplink_switch_interfaces: [ Ethernet1, Ethernet1 ]
        - name: LEAF2
          id: 2
          mgmt_ip: 172.31.0.28/23
          uplink_switch_interfaces: [ Ethernet2, Ethernet2 ]
    - group: POD2
      bgp_as: 65002
      vtep_loopback_ipv4_address: 2.2.2.2
      filter:
        tags: [ "App" ]
      nodes:
        - name: LEAF3
          id: 3
          mgmt_ip: 172.31.0.29/23
          uplink_switch_interfaces: [ Ethernet3, Ethernet3 ]
        - name: LEAF4
          id: 4
          mgmt_ip: 172.31.0.19/23
          uplink_switch_interfaces: [ Ethernet4, Ethernet4 ]
