---
mlag_ibgp_peering_vrfs:
  base_vlan: 3001

tenants:
  - name: MY_FABRIC
    mac_vrf_vni_base: 10000
    vrfs:
      - name: Red
        vrf_vni: 50001
        vrf_id: 1
        # mlag_ibgp_peering_vlan: 3001
        svis:
          - id: 10
            name: 'Ten'
            tags: [ "Web" ]
            enabled: true
            ip_address_virtual: 10.10.10.1/24
            # nodes:
            #   - node: SPINE1
            #     ip_address: 10.10.10.2/24
            #   - node: SPINE2
            #     ip_address: 10.10.10.3/24
          - id: 20
            name: 'Twenty'
            tags: [ "App" ]
            enabled: true
            ip_address_virtual: 10.20.20.1/24
            # nodes:
            #   - node: SPINE1
            #     ip_address: 10.20.20.2/24
            #   - node: SPINE2
            #     ip_address: 10.20.20.3/24
