---
fabric_name: DC_FABRIC

# Set Design Type to L2ls
design:
  type: l2ls

# Spine Switches
l3spine:
  defaults:
    platform: cEOS
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    loopback_ipv4_pool: 10.1.252.0/24
    mlag_peer_ipv4_pool: 10.1.253.0/24
    mlag_peer_l3_ipv4_pool: 10.1.254.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:01
    mlag_interfaces: [ Ethernet5, Ethernet6 ]
  node_groups:
    - group: SPINES
      nodes:
        - name: SPINE1
          id: 1
          mgmt_ip: 172.100.100.101/24
        - name: SPINE2
          id: 2
          mgmt_ip: 172.100.100.102/24

# Leaf Switches
leaf:
  defaults:
    platform: cEOS
    mlag_peer_ipv4_pool: 10.1.253.0/24
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    uplink_switches: [ SPINE1, SPINE2 ]
    uplink_interfaces: [ Ethernet1, Ethernet2 ]
    mlag_interfaces: [ Ethernet3, Ethernet4 ]
  node_groups:
    - group: RACK1
      filter:
        tags: [ "Web" ]
      nodes:
        - name: LEAF1
          id: 3
          mgmt_ip: 172.100.100.103/24
          uplink_switch_interfaces: [ Ethernet1, Ethernet1 ]
        - name: LEAF2
          id: 4
          mgmt_ip: 172.100.100.104/24
          uplink_switch_interfaces: [ Ethernet2, Ethernet2 ]
    - group: RACK2
      filter:
        tags: [ "App" ]
      nodes:
        - name: LEAF3
          id: 5
          mgmt_ip: 172.100.100.105/24
          uplink_switch_interfaces: [ Ethernet3, Ethernet3 ]
        - name: LEAF4
          id: 6
          mgmt_ip: 172.100.100.106/24
          uplink_switch_interfaces: [ Ethernet4, Ethernet4 ]

##################################################################
# Underlay Routing Protocol - ran on Spines
##################################################################

underlay_routing_protocol: OSPF
